#!/bin/bash

# Set identification from install inputs
if [[ -n "${UBUDONGS_USER_NAME//[[:space:]]/}" ]]; then
  git config --global user.name "$UBUDONGS_USER_NAME"
fi

if [[ -n "${UBUDONGS_USER_EMAIL//[[:space:]]/}" ]]; then
  git config --global user.email "$UBUDONGS_USER_EMAIL"
fi

# Set gpg signing options
git config --global commit.gpgsign true
git config --global tag.gpgsign true

# Generate SSH keys for git if email is provided
if [[ -n "${UBUDONGS_USER_EMAIL//[[:space:]]/}" ]]; then
  # Output file
  ssh_key_file="$HOME/.ssh/github_${UBUDONGS_USER_EMAIL//[@.]/_}_ed25519"

  if [[ "$PASSPHRASE" != "$CONFIRM_PASSPHRASE" ]]; then
    gum style --foreground "red" "Passphrases do not match. Exiting."
    exit 1
  fi

  # Ask ssh passphrase
  passphrase=$(gum input --prompt "SSH passphrase> ")
  confirm_passphrase=$(gum input --prompt "Confirm SSH passphrase> ")

  ssh-keygen -t ed25519 -C "$UBUDONGS_USER_EMAIL" -f "$ssh_key_file" -N "$passphrase"
fi

# Generate GPG keys for git if name and email are provided
if [[ -n "${UBUDONGS_USER_NAME//[[:space:]]/}" && -n "${UBUDONGS_USER_EMAIL//[[:space:]]/}" ]]; then
  cat >gen-gpg-batch <<EOF
  Key-Type: rsa
  Key-Length: 4096
  Subkey-Type: rsa
  Subkey-Length: 4096
  Name-Real: $UBUDONGS_USER_NAME
  Name-Email: $UBUDONGS_USER_EMAIL
  Name-Comment: Generated by Ubudongs Installer
  Expire-Date: 0
EOF
  gpg --batch --generate-key gen-gpg-batch
  rm gen-gpg-batch

  GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG "$UBUDONGS_USER_EMAIL" | grep sec | awk '{print $2}' | cut -d'/' -f2)
  git config --global user.signingkey "$GPG_KEY_ID"
fi