#!/bin/bash

# Read user information: name, email, folder
read_user_info() {
  local user_num=$1
  local -n name_ref=$2
  local -n email_ref=$3
  local -n folder_ref=$4

  log_skipline
  if [[ -z "$user_num" ]]; then
    log_info "Getting information for user"
  elif [[ $user_num -gt 0 ]]; then
    log_info "Getting information for user $user_num"
  fi

  while true; do
    local system_name=$(getent passwd "$USER" | cut -d ':' -f 5 | cut -d ',' -f 1)
    name_ref=$(gum input --placeholder "Enter full name" --value "$system_name" --prompt "Name> ")
    email_ref=$(gum input --placeholder "Enter email address" --prompt "Email> ")
    folder_ref=$(gum input --placeholder "Enter folder name (e.g., ~/projects/personal)" --value "~/Work" --prompt "Folder> ")

    if [[ -n "$name_ref" && -n "$email_ref" && -n "$folder_ref" ]]; then
      break
    else
      gum style --foreground "red" "All fields are required. Please try again."
      log_skipline
    fi
  done
}

# Create git-user folder, for projects, if it doesn't exist
# Updates folder_ref variable to expanded (absolute) path
create_user_folder() {
  local -n folder_ref=$1

  # Expand ~ to home directory
  folder_ref="${folder_ref/#\~/$HOME}"

  if [[ ! -d "$folder_ref" ]]; then
    mkdir -p "$folder_ref"
    log_info "Created user folder at: $folder_ref"
  fi
}

# Create SSH key for Github
create_user_ssh_key() {
  local email=$1

  # SSH key output file
  local ssh_key_file="$HOME/.ssh/github_${email//[@.]/_}_ed25519"

  log_skipline
  log_info "Create a new SSH key for Github at: $ssh_key_file"
  log_action "Prepare to fill the new passphrase"

  # Ask ssh passphrase until they match
  while true; do
    local passphrase=$(gum input --prompt "SSH passphrase> " --password)
    local confirm_passphrase=$(gum input --prompt "Confirm SSH passphrase> " --password)

    if [[ "$passphrase" == "$confirm_passphrase" ]]; then
      break
    else
      gum style --foreground "red" "Passphrases do not match. Please try again."
      log_skipline
    fi
  done

  ssh-keygen -t ed25519 -C "$email" -f "$ssh_key_file" -N "$passphrase"
  log_success "SSH key created at: $ssh_key_file"

  echo "$ssh_key_file"
}

# Create GPG key for Git signing
create_user_gpg_key() {
  local name=$1
  local email=$2
  local user_num=$3

  log_skipline
  log_info "Create a new GPG key for Git signing"
  log_action "Prepare to fill the new passphrase"

  local comment="Generated by Ubudongs Installer"
  if [[ -n "$user_num" ]]; then
    comment="$comment - User $user_num"
  fi

  cat >gen-gpg-batch <<EOF
  Key-Type: rsa
  Key-Length: 4096
  Subkey-Type: rsa
  Subkey-Length: 4096
  Name-Real: $name
  Name-Email: $email
  Name-Comment: $comment
  Expire-Date: 0
EOF
  gpg --batch --generate-key gen-gpg-batch
  rm gen-gpg-batch

  local gpg_key_id
  gpg_key_id=$(gpg --list-secret-keys --keyid-format LONG "$email" | grep sec | awk '{print $2}' | cut -d'/' -f2)

  log_success "GPG key created with ID: $gpg_key_id"
  echo "$gpg_key_id"
}

# Generate user-specific gitconfig
generate_multi_user_gitconfig() {
  local name=$1
  local email=$2
  local signingkey=$3
  local ssh_key=$4

  {
    echo "[user]"
    echo "    name = $name"
    echo "    email = $email"
    if [[ -n "$signingkey" ]]; then
      echo "    signingkey = $signingkey"
      echo ""
      echo "[commit]"
      echo "    gpgsign = true"
      echo ""
      echo "[tag]"
      echo "    gpgsign = true"
    fi
  } > "$HOME/.gitconfig-${email//[@.]/-}"
}

# Generate global gitconfig to include user configs
generate_multi_global_gitconfig() {
  local folders_path=$1
  local emails=$2

  IFS='|' read -ra email_array <<< "$emails"
  IFS='|' read -ra folder_array <<< "$folders_path"

  # Create includeIf sections for each user folder
  {
    for i in "${!email_array[@]}"; do
      echo "[includeIf \"gitdir:${folder_array[$i]}/\"]"
      echo "    path = $HOME/.gitconfig-${email_array[$i]//[@.]/-}"
      echo ""
    done
  } > "$HOME/.gitconfig"
}

# Generate single user gitconfig
generate_single_user_gitconfig() {
  local name=$1
  local email=$2
  local signingkey=$3
  local ssh_key=$4

  {
    echo "[user]"
    echo "    name = $name"
    echo "    email = $email"
    if [[ -n "$signingkey" ]]; then
      echo "    signingkey = $signingkey"
      echo ""
      echo "[commit]"
      echo "    gpgsign = true"
      echo ""
      echo "[tag]"
      echo "    gpgsign = true"
    fi
  } > "$HOME/.gitconfig"
}

print_header "Git configuration"

# Copy global git config file if not exists
git_config="$HOME/.config/git"
if [[ ! -f "$git_config/config" ]]; then
  log_skipline
  log_info "Copying Git global configuration file to ${git_config}/config..."
  mkdir -p "$git_config"
  cp $UBUDONGS_PATH/configs/git/config "${git_config}/config"
fi

num_git_users=$(gum choose {0..2} --header "Select number of git users to configure")

# Generate user git configurations
# For multiple users, create separate gitconfig files and a global gitconfig to include them
if [[ "$num_git_users" -gt 1 ]]; then
  log_skipline
  log_info "Configuring Git for $num_git_users user(s)"

  for (( i=1; i<=num_git_users; i++ )); do
    read_user_info "$i" "user_name_$i" "user_email_$i" "user_folder_$i"
    create_user_folder "user_folder_$i"
    ssh_key_file=$(create_user_ssh_key "${!user_email_$i}")
    gpg_key_id=$(create_user_gpg_key "${!user_name_$i}" "${!user_email_$i}" "$i")
    generate_multi_user_gitconfig "${!user_name_$i}" "${!user_email_$i}" "$gpg_key_id" "$ssh_key_file"
  done

  # Generate global gitconfig including all user configs
  all_folders=""
  all_emails=""
  for (( i=1; i<=num_git_users; i++ )); do
    all_folders+="${!user_folder_$i}|"
    all_emails+="${!user_email_$i}|"
  done

  # Remove trailing delimiters
  all_folders="${all_folders%|}"
  all_emails="${all_emails%|}"
  generate_multi_global_gitconfig "$all_folders" "$all_emails"
  
  log_skipline
  log_success "Git configured" 
# For single user, create single root gitconfig file
elif [[ "$num_git_users" -eq 1 ]]; then
  log_skipline
  log_info "Configuring Git for single user"

  read_user_info "" "user_name" "user_email" "user_folder"
  create_user_folder "user_folder"
  ssh_key_file=$(create_user_ssh_key "$user_email")
  gpg_key_id=$(create_user_gpg_key "$user_name" "$user_email" "")
  generate_single_user_gitconfig "$user_name" "$user_email" "$gpg_key_id" "$ssh_key_file"
  log_skipline
  log_success "Git configured"
else
  log_skipline
  log_info "Skipping Git user information setup"
fi

print_footer
