#!/bin/bash

print_header "Git configuration"

# Set identification from install inputs
if [[ -n "${UBUDONGS_USER_NAME//[[:space:]]/}" ]]; then
  git config --global user.name "$UBUDONGS_USER_NAME"
fi

if [[ -n "${UBUDONGS_USER_EMAIL//[[:space:]]/}" ]]; then
  git config --global user.email "$UBUDONGS_USER_EMAIL"
fi

git_config="$HOME/.config/git"
echo ""
log_info "Copying Git global configuration file to ${git_config}/config..."
mkdir -p "$git_config"
cp $UBUDONGS_PATH/configs/git/config "${git_config}/config"

# Generate SSH keys for git if email is provided
if [[ -n "${UBUDONGS_USER_EMAIL//[[:space:]]/}" ]] && gum confirm "Install Github SSH keys?"; then
  # Output file
  ssh_key_file="$HOME/.ssh/github_${UBUDONGS_USER_EMAIL//[@.]/_}_ed25519"

  echo ""
  log_info "Create a new SSH key for Github at: $ssh_key_file"
  log_action "Prepare to fill the new passphrase"

  # Ask ssh passphrase
  while true; do
    passphrase=$(gum input --prompt "SSH passphrase> " --password)
    confirm_passphrase=$(gum input --prompt "Confirm SSH passphrase> " --password)

    if [[ "$passphrase" == "$confirm_passphrase" ]]; then
      break
    else
      gum style --foreground "red" "Passphrases do not match. Please try again."
      echo ""
    fi
  done

  ssh-keygen -t ed25519 -C "$UBUDONGS_USER_EMAIL" -f "$ssh_key_file" -N "$passphrase"
fi

# Generate GPG keys for git if name and email are provided
if [[ -n "${UBUDONGS_USER_NAME//[[:space:]]/}" && -n "${UBUDONGS_USER_EMAIL//[[:space:]]/}" ]] && gum confirm "Install Github GPG keys?"; then
  echo ""
  log_info "Create a new Github GPG key for Git signing"
  log_action "Prepare to fill the new passphrase"

  cat >gen-gpg-batch <<EOF
  Key-Type: rsa
  Key-Length: 4096
  Subkey-Type: rsa
  Subkey-Length: 4096
  Name-Real: $UBUDONGS_USER_NAME
  Name-Email: $UBUDONGS_USER_EMAIL
  Name-Comment: Generated by Ubudongs Installer
  Expire-Date: 0
EOF
  gpg --batch --generate-key gen-gpg-batch
  rm gen-gpg-batch

  gpg_key_id=$(gpg --list-secret-keys --keyid-format LONG "$UBUDONGS_USER_EMAIL" | grep sec | awk '{print $2}' | cut -d'/' -f2)
  git config --global user.signingkey "$gpg_key_id"
  git config --global commit.gpgsign true
  git config --global tag.gpgsign true
fi

echo ""
log_success "Git configured"
print_footer
