# Overwrite default 'ls' with 'eza' for better visuals
alias ls='eza -lh --group-directories-first --icons=auto'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'

# Add fastfetch alias
if command -v fastfetch &> /dev/null; then
  alias dongs='fastfetch'
fi
